### ISSUE TITLE
Out of tree EBS CSI driver needed for EKS v1.23

### ISSUE THREAD

**Issue by richardcase** [rancher/eks-operator#106]
With EKS v1.23 and higher it requires the use of the out of tree EBS CSI driver. If this isn't available then and PVC will not be bound and pods using the volumes will stay in pending.

This is a problem for creating new clusters and for upgrading clusters from 1.22

Docs: https://docs.amazonaws.cn/en_us/eks/latest/userguide/ebs-csi.html

**PR's**
- [x] https://github.com/rancher/eks-operator/pull/725
- [x] https://github.com/rancher/eks-operator/pull/724

**Comment by sanjay920** [comment]
the aws docs are quite confusing.I added a wiki in the opni repo that our engineers use to get around this problem if it comes in handy https://github.com/rancher/opni/wiki/Install-AWS-EBS-CSI-driver

**Comment by richardcase** [comment]
Thanks @sanjay920

**Comment by richardcase** [comment]
A support utility has been created to handle this until we can include the functionality in eks-operator.

When including in the operator should we automatically enable the EBS CSI addon? Doing this will require that the IAM permissions that Rancher uses will need to be updated (including the docs). Or should it be an opt-in by annotating the namespace?

**Comment by richardcase** [comment]
From discussion with @salasberryfin  & @mjura we thought this would be the best approach:

- Installation of the EBS CSI driver will be optional (as is the case when using the AWS console)
- We will add a new field to `EKSClusterConfigSpec` to indicate that the driver should be installed
- If the field is true we will do all the steps to enable the driver
- Update the EKS create cluster UI to have an option to set this new field. (optionally) In the UI we can also warn the user that additional permissions are required.
- Update the Rancher docs around the minimum EKS permissions: https://ranchermanager.docs.rancher.com/v2.5/reference-guides/amazon-eks-permissions/minimum-eks-permissions

**Comment by salasberryfin** [comment]
On the `eks-operator` side, the issue can be divided in the following tasks:

- [ ] Add new boolean field to `EKSClusterConfigSpec`
- [ ] Implement logic to create OIDC provider and IAM role and install EKS addon
- [ ] Unit tests
- [ ] e2e tests

**Comment by salasberryfin** [comment]
PR was merged and this is now waiting for rancher/dashboard#9043 to be implemented.

**Comment by richardcase** [comment]
@salasberryfin - we'll also need to make an update to the Rancher Docs so that the new permissions are included.

**Comment by salasberryfin** [comment]
Added rancher/rancher-docs#704 to update Rancher docs with the permissions required to enable the add-on.

**Comment by mjura** [comment]
UI and docs were merged, back to testing

**Comment by cpinjani** [comment]
Adjusting the milestone, as the UI/Doc issues are slated for v2.9
cc: @kkaempf @mjura

**Comment by cpinjani** [comment]
Validated on build:
```
v2.9-a57f7025abdd80a2912f7fe53247ef7e1d4993de-head
eks-operator:v1.9.0-rc.9
```
Enabled Out of tree EBS CSI driver while provisioning cluster, its set to _ebsCSIDriver: true_ in config, and the cluster in EKS has the Add-On enabled:
```
time="2024-07-02T10:02:15Z" level=info msg="enabling [ebs csi driver add-on] for cluster [cpinjani-eks29]"
time="2024-07-02T10:02:22Z" level=info msg="cluster [c-t7tm4] finished updating"
```
![image](https://github.com/rancher/eks-operator/assets/73099870/f186ab13-ecee-4b59-a7b7-87c649c7b79c)

However, after cluster becomes Active its set to _ebsCSIDriver: null_ in spec.
Expected value: _ebsCSIDriver: true_

@mjura @salasberryfin Can you please have a look ?

**Comment by salasberryfin** [comment]
Thanks for reporting @cpinjani. Could you confirm if this is null in `upstreamSpec`, `eksConfig` or both?

**Comment by cpinjani** [comment]
null in both, upstreamSpec & eksConfig

**Comment by cpinjani** [comment]
Validation passed on below build, able to set Out of tree EBS CSI driver while creation/edit of cluster. 
`ebsCSIDriver: true` is set in cluster config.

```
v2.9-92f15949d71efb11baf63c878cc2f64bcd25b1e8-head
eks-operator:v1.9.1-rc.6
```
