### ISSUE TITLE
Hosted Rancher migration rollback process not working - "Cluster agent is not connected"

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#136]
### Issue description:
Rancher Hosted Prime currently offers customers the ability to migrate their existing self-hosted Rancher Manager to our hosted environment. The Backup operator is used to take a customer backup and restore it into a new hosted environment. During this process, the server name needs to be updated to a "rancher.cloud" URL and all downstream clusters need to connect to the new URL. In the event something goes wrong, need the ability to rollback any changes made to the downstream clusters so that they point back to the customer's self-managed Rancher Manager. This rollback process which worked in older version (v2.5.x and earlier), seems to no longer work in v2.6.9.

### Business impact:
High risk of migrating customers to Hosted, possibility of no a rollback may deter or prevent customers from migrating to Hosted.

### Troubleshooting steps:

In addition to trying to run the "kubectl -f apply ..." command to reconfigure the cattle-cluster-agent, also tried doing a "kubectl -f delete ..." as well as manually removing the cattle-system, cattle-fleet-system, and cattle-impersonation-system namespaces. Tried restarting rancher and cluster agent pods. Turned on debug logging.

### Repro steps:

Set up a new environment (v2.6.9) or use an existing with a provisioned downstream EKS cluster. Used v1.22.17.
Take a backup of the environment using the Rancher Backup operator (install it if it hasn't already been installed).
Set up a second Rancher Manager environment running 2.6.9 this should have a different servername URL. Don't run rancher (yet).
Restore the backup taken from the first environment.
Update the server-name setting to the name of your second environment.
Install Rancher Manager on the second environment.
Run the cluster registration command on the EKS cluster obtained from the second environment's UI. This should reconfigure the downstream cluster to talk to the second environment instead of the first environment. The first environment should show that the cluster agent is not connected and the second environment should show the cluster as healthy.
Rollback - Run the cluster registration command on the EKS cluster obtained from the first environment's UI. This should reconfigure the cluster to point back to the original Rancher Manager environment. However, this does not appear to work and the cluster remains in a disconnected state.

### Workaround:
Is workararound available and implemented? unknown
What is the workaround:

### Actual behavior:
After attempting rollback, the original Rancher Manager environment shows "Cluster agent is not connected" error for the downstream cluster:

Expected behavior:
After running the kubectl -f apply to reconfigure the cattle-cluster-agent, expecting the agent to reconnect to the original Rancher Manager server and not show any errors. If a new process is needed to rollback a cluster, need to know what that new process is.

**Comment by kkaempf** [comment]
Question: Could this be an operator bug ? (Or is it rather a provisioning bug ?)

**Comment by kkaempf** [comment]
This is a provisioning bug, not an operator bug.

**Comment by kkaempf** [comment]
@mjura can you take a look at the workaround posted by David in JIRA - would this work ?

**Comment by mjura** [comment]
> @mjura can you take a look at the workaround posted by David in JIRA - would this work ?

yes, it seems that workaround which they use works fine. I have already added to my tips and tricks list. 

Btw. problem which they hit was unrelated to operators. It was more like race condition for Rancher cluster-agent.

I think we can consider it as done.
