### ISSUE TITLE
[Feature] K8s 1.26 support

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#137]
See https://github.com/rancher/rancher/issues/41113

Verify that k8s 1.26 works with eks-operator.

Update charts accordingly.

**Comment by mjura** [comment]
As follow up task we have to implement `eksVersions` UI proxy call https://github.com/rancher/eks-operator/issues/157

**Comment by furkatgofurov7** [comment]
> This is blocked by: [rancher/ui#5009](https://github.com/rancher/ui/pull/5009)
> 
> PR#5009 can be merged once [rancher/dashboard#8721](https://github.com/rancher/dashboard/issues/8721) is resolved by the UI team engineers. Putting it to blocked for now.


rancher/ui#5009 is merged, but Rancher UI still shows the old k8s versions (up to v1.24) when creating EKS cluster using Rancher. However, imported EKS cluster with v1.26 k8s version works fine. 

![image](https://github.com/rancher/eks-operator/assets/40443040/6ddcf211-a4e0-40ea-a54c-1126e59cb1ec)

**Comment by furkatgofurov7** [comment]
This can be closed, updating the charts [PR](https://github.com/rancher/charts/pull/2617) is also merged.

**Comment by kkaempf** [comment]
rancher/ui#5009 should be included in 2.7-head (available in Dockerhub) 🤞🏻

**Comment by furkatgofurov7** [comment]
@kkaempf with new UI:

![image](https://github.com/rancher/eks-operator/assets/40443040/14394f4e-f062-4149-bb31-df843678014d)

**Comment by kkaempf** [comment]
Thanks @furkatgofurov7, closing
