### ISSUE TITLE
New imported EKS cluster is not accesible from Cluster Management tab

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#144]
### Issue description: Access to newly created imported EKS downstream cluster from Cluster Management ==> Clusters ==> "Cluster Name" hangs on loading. ** 

Access to: https://<rancher>/dashboard/c/_/manager/provisioning.cattle.io.cluster/fleet-default/  fails.

Access to:  https://<rancher>/dashboard/c/cluster-id/explorer works.

The web browser dev tools show: "Wait for The cluster to become available. It's possible the cluster was created. We suggest checking the clusters page before trying to create another. done immediately."

### Troubleshooting steps:
The EKS DS cluster runs in the same VPC as Rancher. From  ☰ >EXPLORE CLUSTER, the access to the cluster goes fine. ** The cluster runs fine; some applications have been deployed with the fleet.  (CF access-explorecluster-ok)

The access to the cluster from  ☰ > Cluster Management is stuck on loading (CF image1-notloading).

The error on the dev tools web browser is: "TypeError: Cannot read properties of null (reading 'filter') at f.showEskNodeGroupWarning (CF image2-error-clustermanagement)

### Workaround:
Is workararound available and implemented? yes
What is the workaround: Edit the cluster's configuration and performance a minor change; for instance, add a user. The socket connection was established

### Actual behavior:
EKS cluster is not accessible from Cluster Management.

### Expected behavior:
Access to the DS cluster should be working.

### Files, logs, traces:
```
$ curl -s -i -N \
> --http1.1 \
> -H "Connection: Upgrade" \
> -H "Upgrade: websocket" \
> -H "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
> -H "Sec-WebSocket-Version: 13" \
> -H "Authorization: Bearer $TOKEN" \
> -H "Host: $FQDN" \
> -k https://$fqdn/v3/subscribe
HTTP/1.1 101 Switching Protocols

Date: Tue, 14 Feb 2023 18:09:07 GMT
Connection: upgrade
Upgrade: websocket
Sec-WebSocket-Accept: qGEgH3En71di5rrssAZTmtRTyFk= �{"name":"ping","data":{}}�{"name":"ping","data":{}}�{"name":"ping","data":{}}^C
```

**Comment by kkaempf** [comment]
Needs to be reproduced with latest Rancher.

**Comment by salasberryfin** [comment]
Updated JIRA issue requesting extra details after some investigation and not being able to reproduce the problem.

Considering where the error is being triggered in `showEksNodeGroupWarning` https://github.com/rancher/dashboard/blob/0e996c7fa31f9dcd02931548b3b1ab888e960c07/shell/detail/provisioning.cattle.io.cluster.vue#L388, it looks like it is related to Node Group configuration.

**Comment by salasberryfin** [comment]
Confirmed in SURE-5920 that the customer is no longer affected by the issue.
