### ISSUE TITLE
Implement UI proxy functions for EKS

### ISSUE THREAD

**Issue by mjura** [rancher/eks-operator#157]
This needs to be done as for AKS
https://github.com/rancher/rancher/blob/release/v2.7/pkg/api/norman/customization/aks/handler.go#L106

**Comment by furkatgofurov7** [comment]
I have started implementing this, however after some research with @mjura currently it seem there is a limitation where we do not have a way to fetch EKS supported k8s cluster versions using API, ref: https://github.com/aws/aws-sdk-go-v2/issues/1906

One way to get the list of supported k8s versions in EKS by parsing https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html page and fetching the versions, however there are some implications, such:

- what if content will move to different location in the future
- page will not be available for other reasons

**Comment by furkatgofurov7** [comment]
@richardcase as discussed offline, if you have any other alternative directions that we could take, please share on this issue, thanks!

**Comment by richardcase** [comment]
@furkatgofurov7 - the idea I had to use SSM would give all versions of EKS ever....so not very helpful :rofl: 

I guess as a temporary solution, we could have a GHA workflow that executes every night and queries the page you mention and compares it to the versions we statically stored somewhere. Its not ideal at all.

**Comment by kkaempf** [comment]
API not available from AWS, closing.
