### ISSUE TITLE
Flaky test in Rancher CI

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#184]
## SURE-6455

`test_editing_eks_cluster_gives_temp_creds_annotation` is flaky

See https://github.com/rancher/rancher/blob/9a33c24de30c81f2ecd900d923d16d7fb2020929/tests/integration/suite/test_kontainer_engine_annotations.py#L87

**Comment by mjura** [comment]
According to my findings this test is not causing any problems for Drone CI. It is also test for really old KEv1 which was deprecated and it can be easily removed.
