### ISSUE TITLE
[ENHANCEMENT] - Add tagging of Volumes when EKS provisions cluster

### ISSUE THREAD

**Issue by jdunhamvrtx** [rancher/eks-operator#205]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature enhancement

**Steps to reproduce (least amount of steps as possible):**
Set Tag Enforcement on EC2 volume resource, provision EKS cluster with RMC filling out (all) tags as required.

**Result:**
RMC is not adding the volume tag so the cluster fails to come up with error, 

{
  "allowed": false,
  "explicitDeny": true,
  "matchedStatements": {
    "items": [
      {
        "statementId": "ScpEnforceTagsApp",
        "effect": "DENY",
       "principalGroups": {
          "items": []
        },
        "actions": {
          "items": [
            {
              "value": "ec2:RunInstances"
            }
          ]
        },
        "resources": {
          "items": [
            {
              "value": "arn:aws:ec2:*:*:instance/*"
            },
            {
              "value": "arn:aws:ec2:*:*:volume/*"
            }
          ]
        },

**Other details that may be helpful:**
It would be useful to get a widget similar to how AWS allows tag application in the launch template somewhere in the RMC 'wizard' for EKS creation. A single webpage module that allows me to create the key:value tag and then asks me what this tag applies to (three fields, two text input, last as a multiselect). This would consolidate the number of times I repeat the same tags throughout the wizard.

**Environment information**
- Rancher version  RMC 2.5.7
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type: Cloud / AWS managed
- Machine type Ec2 / EKS managed
- Kubernetes version 1.18

gz#16840

**Comment by richardcase** [comment]
Updated repo instructions on PR #206

**Comment by cpinjani** [comment]
Validated as fixed on build:
`2.7-head - 95f0b50, eks-operator:v1.2.2-rc3
`

**QA Test Results** - :white_check_mark:

| Test Case | Result (Tags applied to EC2 volumes as well)
| -- | --
| Create downstream EKS NodeGroup with Rancher managed Launch Template with Instance Resource tags | :white_check_mark: 
| Create downstream EKS cluster and NodeGroup with Custom Launch Template with Instance Resource tags specified in LT| :white_check_mark: 
| Import downstream EKS cluster and NodeGroup and add tags to new Node groups | :white_check_mark:  
| Create downstream EKS cluster and NodeGroup with Terraform (Rancher managed LT) and add tags to new Node groups | :white_check_mark:  
| Create downstream EKS cluster and NodeGroup with Terraform (Custom managed LT) with tags specified in LT | :white_check_mark:  
| Provision downstream EKS on v2.7.5 => upgrade Rancher to v2.7-head => Verify tags can be applied to running EKS cluster Node groups, post rancher-server upgrade |  :white_check_mark: 
| Provision downstream EKS on v2.7.5 => upgrade Rancher to v2.7-head => Verify tags can be applied to new provisioned EKS cluster Node groups, post rancher-server upgrade | :no_entry: 

Opened an issue for tags modification on UI: https://github.com/rancher/dashboard/issues/9405

**Comment by kkaempf** [comment]
Internal ref: sure-3188
