### ISSUE TITLE
Sequential upgrade of multiple node groups version not completing successfully

### ISSUE THREAD

**Issue by cpinjani** [rancher/eks-operator#209]
**Rancher version:**
```
2.7-head - 95f0b50
eks-operator:v1.2.2-rc3
```

Installation option: Docker
Proxy/Cert Details: Self-signed

**Information about the Cluster**
Kubernetes version: 1.25
Cluster Type: Downstream EKS cluster

**User Information**
What is the role of the user logged in? Standard user

**Describe the bug**
Sequential upgrade of multiple node groups version not completing successfully. In case of simultaneous upgrade of Node groups, it completes successfully.

**Steps**
1. Provision EKS cluster with version less than highest supported one, with more than one node group
2. Upgrade EKS cluster to higher version (At this step, only CP is upgraded) and UI displays - "A new cluster version has been selected. Once completed you may come back and upgrade the node version."
3. Out of 2 node pools, upgrade only one to CP version
4. Now update the remaining Node group to CP version using Ranhcer UI

**Expected Result**
Sequential upgrade of multiple node groups version must complete successfully

**Screenshots**
After step 4, below is Cluster state on AWS:
![image](https://github.com/rancher/eks-operator/assets/73099870/25aae273-651f-476a-94cb-0cdb2d6c79f3)

Rancher shows operation completed, but other Node group is still on lower version and Cluster Edit still shows and upgrade available.
![image](https://github.com/rancher/eks-operator/assets/73099870/90aa2900-d65e-4846-b742-663ca946399f)

cc: @rancher/highlander 

**PR's**
- [x] https://github.com/rancher/eks-operator/pull/273
- [x] https://github.com/rancher/eks-operator/pull/274
- [x] https://github.com/rancher/eks-operator/pull/275
- [x] https://github.com/rancher/charts/pull/3155
- [x] https://github.com/rancher/rancher/pull/43212

**Comment by kkaempf** [comment]
tentatively adding to Q3 milestone, not sure about actual priority 🤔

**Comment by mjura** [comment]
It seems that it works fine, only one condition was to wait until `UpstreamSpec` will be synced again with `AppliedSpec`

Here are logs from `eks-operator`

```
time="2023-10-09T12:56:45Z" level=info msg="waiting for cluster [c-9qmhv] to finish updating"
time="2023-10-09T12:57:15Z" level=info msg="waiting for cluster [c-9qmhv] to finish updating"
time="2023-10-09T12:57:45Z" level=info msg="waiting for cluster [c-9qmhv] to finish updating"
time="2023-10-09T12:58:17Z" level=info msg="cluster [c-9qmhv] finished updating"
time="2023-10-09T13:21:32Z" level=info msg="waiting for cluster [c-9qmhv] to update nodegroups [mjura-nd1]"
time="2023-10-09T13:22:03Z" level=info msg="waiting for cluster [c-9qmhv] to update nodegroups [mjura-nd1]"
time="2023-10-09T13:22:34Z" level=info msg="waiting for cluster [c-9qmhv] to update nodegroups [mjura-nd1]"
time="2023-10-09T13:23:06Z" level=info msg="waiting for cluster [c-9qmhv] to update nodegroups [mjura-nd2]"
time="2023-10-09T13:23:37Z" level=info msg="waiting for cluster [c-9qmhv] to update nodegroups [mjura-nd2]"
time="2023-10-09T13:24:08Z" level=info msg="waiting for cluster [c-9qmhv] to update nodegroups [mjura-nd2]"
time="2023-10-09T13:36:28Z" level=info msg="cluster [c-9qmhv] finished updating"
```

Invalid

**Comment by mjura** [comment]
@cpinjani please re-test and let me know

**Comment by cpinjani** [comment]
Able to reproduce on v2.8-head build.

**Steps**
- Provision EKS cluster with version less than highest supported one, with two node groups: test1 & test2
- Upgrade EKS cluster to higher version (At this step, only CP is upgraded) and UI displays - "A new cluster version has been selected. Once completed you may come back and upgrade the node version."
- Out of 2 node pools, upgrade only test2 to CP version, and let sync complete
- Now update the test1 nodegroup to CP version, test1 nodegroup updates to latest version but downgrades to lower version again

![image](https://github.com/rancher/eks-operator/assets/73099870/32877519-009f-428b-823d-d12675b77084)

**Comment by valaparthvi** [comment]
I also noticed that if the first update in line is an invalid update (for e.g. Both public and Private access as False) followed by another valid update (for e.g. add a label to the nodegroup), the cluster is stuck with the invalid update and there's no way of reverting it.

**Comment by cpinjani** [comment]
Validated as fixed on build:
```
v2.8-136e9ccd054866dd0f504abfa592dc2b519179c9-head
eks-operator:v1.3.0-rc4
```
Sequential & simultaneous upgrade of multiple node groups version completing successfully.
