### ISSUE TITLE
EKS: Rancher managed launch template information not being displayed for Nodegroup

### ISSUE THREAD

**Issue by cpinjani** [rancher/eks-operator#242]
**Setup**
```
Rancher version: v2.7.7-rc4
Browser: Chrome Latest

```
**Describe the bug**
Rancher managed launch template information not being displayed for Nodegroup. The same is being displayed in case of Custom Launch template.

**To Reproduce**
- Start to create downstream EKS cluster
- Can keep all the settings default and create Nodegroup using Rancher managed launch template (default behavior)
- Wait for the cluster to be Active
- Edit cluster and check Launch template information for the above created Nodegroup

**Expected Result**
Nodegroup must display Launch template information as "Rancher Managed Launch Template" and appropriate Template version, so that User is able to edit Nodegroup details
(check v2.7.5 screenshot below)

**Screenshots**
Rancher managed LT:
![image](https://github.com/rancher/dashboard/assets/73099870/070da14f-63e4-4df8-820f-f035a6790f6e)

Custom LT:
![image](https://github.com/rancher/dashboard/assets/73099870/1d8dc245-255a-4326-9332-8e85258f30f1)

Rancher managed LT (v2.7.5):
![image](https://github.com/rancher/dashboard/assets/73099870/44c9c3b7-5fa3-4332-a345-ba9225dccac1)

Found while validating https://github.com/rancher/rancher/issues/42496

cc: @rancher/highlander

**Comment by Jono-SUSE-Rancher** [comment]
@salasberryfin just a heads up that if this is not a blocker bug, we almost certainly cannot fit this into v2.7.7 so it might need to get forward ported up to 2.8.0 and backported into a future 2.7 milestone.

If it's a blocker level, let me know and we can discuss timelines.

**Comment by salasberryfin** [comment]
Hi @Jono-SUSE-Rancher, we've created release candidate `eks-operator:v1.2.2-rc5` that includes this bug fix and updated the [charts](https://github.com/rancher/charts/pull/2929). The bug is preventing users from modifying the configuration of certain EKS node groups so we can consider this to be a blocker.

**Comment by cpinjani** [comment]
Validated as fixed on build:
```
v2.7-dbac88362ae3bea3f7b912e52dcefaa750133277-head
rancher/eks-operator:v1.2.2-rc6
```
Test Results - :white_check_mark: 
Performed testing on Rancher v2.7-head Fresh install and upgraded setup from 2.7.5 to v2.7-head

| Test Cases |
| -- |
| Create EKS cluster with Nodegroup using Rancher managed Launch Template |
| Create EKS cluster with Nodegroup using Custom Launch Template |
| Edit EKS cluster Nodegroup configuration having Rancher managed Launch Template |
| Upgrade EKS cluster K8s version having Rancher managed Launch Template |
| Scale up / Scale down EKS cluster with Nodegroup having Rancher managed Launch Template |

![image](https://github.com/rancher/eks-operator/assets/73099870/a0ab001e-7bb1-41fb-a401-f5f52194146b)

**Comment by cpinjani** [comment]
Closing issue based on above validation results.
