### ISSUE TITLE
EKS on Rancher does not go into updating state when a change is made from cloud console

### ISSUE THREAD

**Issue by valaparthvi** [rancher/eks-operator#277]
**Versions:**
Rancher: v2.8.0-rc1
EKS Operator: rancher-eks-operator:103.0.0+up1.3.0-rc4

**Steps to Reproduce:**
1. Import/Create an EKS cluster
2. From AWS Console, add/delete nodegroup or upgrade the k8s version.
3. Check the EKS cluster on Rancher

**Actual Results:**
EKS cluster on Rancher remains `Active` while the cluster is updating in AWS console. After the update is complete on AWS Console, wait for a few minutes and refresh Rancher, the new changes should be visible.

**Expected Results:**
EKS cluster on Rancher must go into `Updating` state while the cluster is updating in AWS console and become `Active` once all the updates have been made.

**Comment by mjura** [comment]
We do not support push notifications from Cloud Provider to Rancher when there are so events happening. Status change from "Active" to "Upgrading" or "In Progress" can be done only by eks-operator when there is some change applied in Rancher UI. 

We are synchronizing states of upstream kubernetes clusters back to Rancher Manager, but it is done every 15 minutes. Operation mentioned in step 2 are shorter than 15 minutes, so the state of cluster won't be changed in Rancher UI only final result of spec will be used to upgrade EKS config on Rancher site.

Nothing to do for us.

wont-fix
