### ISSUE TITLE
Unable to upgrade NodeGroup k8s version from Rancher

### ISSUE THREAD

**Issue by valaparthvi** [rancher/eks-operator#278]
**Versions:**
Rancher: v2.8.0-rc1
EKS Operator: rancher-eks-operator:103.0.0+up1.3.0-rc3

Rancher is installed using Helm.

**Steps to Reproduce:**
1. Create/Import an EKS cluster.
2. Upgrade the ControlPlane K8s version either from Rancher or AWS Console, does not matter.
3. Upgrade the NodeGroup K8s version from Rancher

**Actual Results:**
Rancher does not do anything. It does not go into `Updating` state and NodeGroups are not upgraded.

**Expected Results:**
Rancher must be able to upgrade the NodeGroups K8s version.

**Comment by cpinjani** [comment]
Can you try with v2.8-head & eks-operator:v1.3.0-rc4, Nodegroup upgrade seems working for me

**Comment by valaparthvi** [comment]
@cpinjani you're right, it works on the latest version. Thanks for pointing it out.
