### ISSUE TITLE
[Backport][v2.7] k8s 1.27 support 

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#326]
refers to rancher/rancher#44098, rancher/rancher#44111

**Comment by mjura** [comment]
Support for K8s v1.27 in GKE operator in Rancher v2.7 works fine

![Image](https://github.com/rancher/eks-operator/assets/4455471/a607b7fc-aeb2-4f1c-8003-6b66ee501189)

**Comment by valaparthvi** [comment]
Tested with the following steps:
1. Installed rancher v2.7-head on k3s v1.26.9.
2. Installed eks-operator-crd and eks-operator --version 103.0.0+up1.3.0.
3. Provisioned and imported EKS cluster.
4. Updated both the clusters and validated the update.
5. Downgraded to --version 102.1.4+up1.2.2
6. Updated both the clusters and validated the update.
7. Deleted the operator charts.
8. Updated both the clusters.
9. Re-installed both the charts.
10. **The last updated cluster in line was only updated; eks-operator did not take into account the first cluster.**
11. Upgraded k3s to v1.27.9
12. updated the imported and provisioned EKS cluster.
13. upgrade the helm charts to latest
14. updated the imported and provisioned EKS cluster.

Overall, things work as expected, except:
1. https://github.com/rancher/dashboard/issues/9519
2. When the operator charts are deleted and clusters are updated; reinstalling the operator charts only updates the last cluster in line. (This behavior is noticeable in other operator charts too.)
3. `.spec.chart.metadata.annotations.catalog.cattle.io/kube-version: '>= 1.20.0-0 < 1.28.0-0' has `1.20.0-0` as the lowest supported version, but the description says `1.23.0-0`. This behavior is consistent in both v1.3.0 and v1.2.2.

<details><summary>eks-operator YAML</summary>
<p>
```yaml
apiVersion: catalog.cattle.io/v1
kind: App
metadata:
  name: eks-operator
  namespace: cattle-system
spec:
  chart:
    metadata:
      annotations:
        catalog.cattle.io/auto-install: rancher-eks-operator-crd=match
        catalog.cattle.io/certified: rancher
        catalog.cattle.io/hidden: 'true'
        catalog.cattle.io/kube-version: '>= 1.20.0-0 < 1.28.0-0'
        catalog.cattle.io/namespace: cattle-system
        catalog.cattle.io/os: linux
        catalog.cattle.io/permits-os: linux,windows
        catalog.cattle.io/provides-gvr: eksclusterconfigs.eks.cattle.io/v1
        catalog.cattle.io/rancher-version: '>= 2.8.0-0 < 2.9.0-0'
        catalog.cattle.io/release-name: rancher-eks-operator
        catalog.cattle.io/scope: management
      apiVersion: v2
      appVersion: 1.3.0
      description: A Helm chart for provisioning EKS clusters
      home: https://github.com/rancher/eks-operator
      name: rancher-eks-operator
      sources:
        - https://github.com/rancher/eks-operator
      version: 103.0.0+up1.3.0
    values:
      additionalTrustedCAs: false
      eksOperator:
        image:
          repository: rancher/eks-operator
          tag: v1.3.0
      global:
        cattle:
          systemDefaultRegistry: ''
      httpProxy: ''
      httpsProxy: ''
      noProxy: ''
      nodeSelector: {}
      priorityClassName: ''
      tolerations: null
  helmVersion: 3```
</p>
</details>

**Comment by valaparthvi** [comment]
https://github.com/rancher/gke-operator/issues/285#issuecomment-1918986263

**Comment by valaparthvi** [comment]
Re-opening this since it will need to be tested on 2.7.11-rc.

**Comment by valaparthvi** [comment]
Tested this issue again on 2.7.11-head on the staging registry.
It works as expected.
