### ISSUE TITLE
Migrate to AWS SDK v2

### ISSUE THREAD

**Issue by richardcase** [rancher/eks-operator#336]
The AWS SDK v1 (which is used by this project) is moving to maintenance mode  July 2024 and will be completely out of support July 2025[^1].

With the long deprecation policy of Rancher we will still have the eks-operator around when the AWS SDK v1 moves out of support. We need to update the operator and migrate to v2 of the SDK.

AWS have published a migration guide[^2] that we can use to understand the changes needed.

[^1]: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/
[^2]: https://aws.github.io/aws-sdk-go-v2/docs/migrating/

**PR's for eks-operator to main**
- [x] https://github.com/rancher/eks-operator/pull/400/
- [x] https://github.com/rancher/eks-operator/pull/426

**PR's for eks-operator to v2.9**
- [x] https://github.com/rancher/eks-operator/pull/439

**PR's for Rancher to v2.9**
- [x] https://github.com/rancher/rancher/pull/44900

**Comment by kkaempf** [comment]
Tentatively setting milestone to v2.9.0

@richardcase @davidstauffer - any strong reasons to do it earlier ?

**Comment by richardcase** [comment]
@kkaempf - whats the timeframe for the v2.9.0 release?

**Comment by kkaempf** [comment]
> @kkaempf - whats the timeframe for the v2.9.0 release?

approx. KubeCon US 2024 😉

**Comment by mjura** [comment]
Try to cover list of available https://github.com/rancher/ui/blob/master/lib/shared/addon/utils/amazon.js#L705

**Comment by cpinjani** [comment]
Validated on build, Fresh install setup + upgraded setup from v2.8.3 -> v2.9-head
```
v2.9-c9be13b09329bbee60a5f6419d500198f83c44d1-head
104.0.0+up1.4.0-rc9
```
EKS sanity checks and P0 scenarios passed - :white_check_mark:
