### ISSUE TITLE
[SURE-3789] Users do not have the ability to select an existing NodeInstanceRole for EKS.

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#352]
## SURE-3789

The Rancher users do have the option to predefine and select the Cluster IAM role. However, users do not have the ability to select an existing NodeInstanceRole. Instead, a cloud formation stack is automatically generated to provision a new IAM Instance Role. This weakens security.

> Currently, the internal security police dont allow then to simple create/copy/paste access and secret keys on Rancher to create credentials to import EKS. From the customer: "Our polices only support assumption of a custom role to be able to provide access to the EKS cluster"

**Comment by yiannistri** [comment]
The functionality described above is already implemented. Users are able to select a predefined node instance role when adding a new managed node group.
