### ISSUE TITLE
security: setup github workflow for image scanning

### ISSUE THREAD

**Issue by mjura** [rancher/eks-operator#412]
As follow up from https://github.com/rancherlabs/image-scanning/issues? q=is%3Aissue+is%3Aopen+label%3Ateam%2Fhighlander we would like setup github workflow which will be scanning images for security vulnerabilities

Example: https://github.com/rancher-sandbox/rancher-turtles/blob/main/.github/workflows/trivy.yml

**Comment by furkatgofurov7** [comment]
GH workflow for image scanning is already configured and running in the repo: https://github.com/rancher/eks-operator/blob/main/.github/workflows/scan.yaml
