### ISSUE TITLE
Investigate defaulting nodegroups to Amazon Linux 2023

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/eks-operator#568]
**Description**

Investigate defaulting node groups to Amazon Linux 2023, we currently create all node groups with Amazon Linux 2 which will be EOL next year https://aws.amazon.com/amazon-linux-2/faqs/

https://github.com/rancher/eks-operator/blob/main/pkg/eks/create.go#L278

**WARNING!!!**
Amazon Linux 2023 is supported by `aws-sdk-go-v2` but there is still missing support for GPU in Amazon Linux 2023 for EKS. It has to be updated later on. Please DON'T RESOLVE THIS ISSUE before `AMITypesAl2X8664Gpu` is also updated.
https://github.com/rancher/eks-operator/blob/main/pkg/eks/create.go#L284

**PR:**
- [x] https://github.com/rancher/eks-operator/pull/580
- [x] https://github.com/rancher/eks-operator/pull/581
- [x] https://github.com/rancher/eks-operator/pull/790
- [x] https://github.com/rancher/eks-operator/pull/789
- [ ] https://github.com/rancher/eks-operator/pull/987
- [ ] https://github.com/rancher/eks-operator/pull/988

**Comment by thehejik** [comment]
The GPU part doesn't work (EKS with `Enabled GPU` flag) when provisioning in `eu-central-2` region. The new GPU AMI is not available.
![image](https://github.com/user-attachments/assets/d56dc4dd-aeb2-403f-a20c-8cb5862142d1)

**Comment by kkaempf** [comment]
Waiting for AWS to support new Amazon Linux 2023 with GPU support

**Comment by kkaempf** [comment]
Is that something we should mention in the Rancher release notes ?
