### ISSUE TITLE
Suggestions for waiting until the AWS cluster is actually deleted

### ISSUE THREAD

**Issue by lsh9159** [rancher/eks-operator#702]
Hello,

While using EKS-operator in my project, I found something to suggest.

I found that when the EKSClusterConfig CR is deleted, it waits for the nodegroup to be deleted, but does not wait for the cluster to be deleted.
 Because of this, resource conflicts often occurred when creating an EKSClusterConfig with the same name immediately after deleting it.
To solve this, could you consider waiting for the cluster to actually be deleted as well?

pull request : https://github.com/rancher/eks-operator/pull/703

**Comment by mjura** [comment]
It needs to be triage

**Comment by mjura** [comment]
It is not needed, currently this behavior is reported properly
