### ISSUE TITLE
Adding EKS cluster breaks Rancher

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#83]
~https://github.com/rancher/rancher/issues/41299~

(was SURE-5647, closed)

**Comment by kkaempf** [comment]
See also #82 and #84

**Comment by alexander-demicev** [comment]
https://github.com/rancher/rancher/pull/40118

**Comment by cpinjani** [comment]
@alexander-demicev Can you link the corresponding PR which fixed this issue and provide QA template, thanks.

**Comment by alexander-demicev** [comment]
@cpinjani sure, where can I find the template?

**Comment by alexander-demicev** [comment]
@cpinjani I wasn't able to reproduce the bug, what should we do in this case?

**Comment by cpinjani** [comment]
@kkaempf @mbologna Please advise on this ^

**Comment by mbologna** [comment]
> @kkaempf @mbologna Please advise on this ^

By reading the whole issue it is not clear to me if you were able to reproduce it @cpinjani ?

**Comment by cpinjani** [comment]
As discussed in Highlander standup, closing it as not reproducible.
