### ISSUE TITLE
(SURE-4552) Ability to configure agent deployments per cluster

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#86]
Ability to configure agent deployments per cluster

See also https://github.com/rancher/rancher/issues/41035

### Business case

AWS - EKS clusters utilized two node groups. One of the node groups leveraged EC2 on-demand instances and the other - spot instances (within auto-scaling groups). The on-demand node group nodes were assigned a custom taint (i.e., platform/node-lifecycle=NoSchedule) to ensure that only specific application workloads were being scheduled on those particular nodes. Alternatively, for the more ephemeral / least critical application workloads, the preference was to schedule them onto the spot instances / node-groups.  Therefore, within the default configuration, when the cattle-cluster-agent pods were being scheduled, they were always getting assigned spot instance because of the custom taint being added (above), causing various flavors of instability within the cluster instance of Rancher UI manager.  https://rancher.com/docs/rancher/v2.5/en/cluster-provisioning/rke-clusters/rancher-agents/#scheduling-rules

The solution would be to provide a method for setting custom parameters to override cattle-cluster-agent and fleet-agent settings at a per cluster level or when deploying rancher via any of the supported deployment options (i.e., helm). (we are focusing on the per-cluster configuration but should acknowledge the original ask).

There are two major asks for configuring agent deployments:

Setting Tolerations and Affinity Rules (Rancher Federal)
Setting Resource Limits

As Rancher does not have a unified cluster interface for every type of cluster consideration needs to be given to how we present these options in each distribution and we may wish to do a phased rollout, the customer's requesting this functionality use.

We should also add RKE1 to any MVP as well.

### Original Requests:

Provide a taint directly onto the target "on-demand" nodes of "[cattle.io/cluster-agent=true:NoSchedule](http://cattle.io/cluster-agent=true:NoSchedule)", given that there is already an existing toleration for that scenario Outside of doing a patch of the cattle-cluster-agent deployment directly, or leveraging gitops solutions to synchronize diffs from underlying git repo (i.e., via kustomize/k8s manifests), there was no alternative solution that would guarantee that somewhere down the line (that we could think of), a subsequent process wouldn't override said patch (i.e., rancher upgrade) and blow away updates.

The cattle-cluster-agent gets deployed where there are not sufficient resources, and therefore want to define resource limits. They also mention it as good kubernetes practice to always operate with resource limits

Resource limits CAN be set on cattle-cluster-agent using kubernetes patch like RFed, but it is cumbersome, and should be settable in Rancher UI

**Comment by kkaempf** [comment]
@a-blender are there eks-operator specific requests for rancher/rancher#41035 ?

**Comment by a-blender** [comment]
@kkaempf AFAIK, the ability to configure agent deployments per cluster is priority for EKS and RKE2 right now. It will have to be implemented for all the hosted providers though. I'm working on the default structs, settings, and later backend logic that all cluster types (including EKS) use to configure the cluster-agent. It's also on the UI team to implement the specified field options -- namely node affinity, resource limits, and additional tolerations -- in the Rancher UI for each hosted provider, but that is not the highlander team.

There's nothing for you to do at the moment here, I believe but the Highlander team should follow along with the internal discussion on this feature.

**Comment by kkaempf** [comment]
Closing as of last comment.
