### ISSUE TITLE
(SURE-4066) EKS cluster via terraform fails when using a custom AMI in a launch template

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#90]
### Issue description:

When using a custom launch template with an AMI ID, the creation of the cluster via terraform will fail with an AWS exception, due to an amiType being specified in the CreateNodegroup call [2].

The eks-operator appears to default to specifying an amiType when image_id is null [1]. As would be the case when the AMI is specified in the launch template.

In the Rancher UI, a describe of the launch template is done first, and the image_id for the cluster is pre-populated as a convenience. When using terraform this requires manual AWS provider actions, but is also unexpected.

Another approach could be to perform this describe in the eks-operator itself, so that the correct CreateNodegroup can occur, ie. if the launch template defines an AMI, don't specify an amiType in the call.

### Repro steps:

Create a launch template, specify an AMI in the LT, the customer also specifies userdata and a security group however this should not be necessary.
Create the EKS cluster using terraform (example attached) using the launch template ID.

### Workaround:
Is workararound available and implemented? yes
What is the workaround: Specify image_id also for the eks_config_v2 to match what is in the launch template (this is a convenience the Rancher UI adds). In my interpretation, the value of image_id doesn't appear to matter, as the launch template takes precedence [3].

### Actual behavior:

Cluster is fails to provision causing an AWS API exception

### Expected behavior:
Cluster is created as in the Rancher UI

### Files, logs, traces:

You cannot specify an AMI Type other than CUSTOM, when specifying an image id in your launch template

[1] https://github.com/rancher/eks-operator/blob/master/controller/nodegroup.go#L242-L248

[2] https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html#AmazonEKS-CreateNodegroup-request-amiType

[3] https://github.com/rancher/eks-operator/blob/master/controller/eks-cluster-config-handler.go#L867*
*

**Comment by salasberryfin** [comment]
PR is now merged and ready to test.

**Comment by cpinjani** [comment]
Able to reproduce issue on unfixed version:
![image](https://github.com/rancher/eks-operator/assets/73099870/cedf6fb1-7490-4fc7-85d4-07899c597d73)


Validated as fixed on build:
```
v2.7-head - 5f98b0f
eks-operator:v1.2.2-rc2
```

Created EKS cluster via TF using launch template having custom AMI and user-data.
![image](https://github.com/rancher/eks-operator/assets/73099870/7ec8041d-fa4b-4380-87b1-8229358ee210)

Terraform file:
```
terraform {
  required_providers {
    rancher2 = {
      source  = "rancher/rancher2"
      version = "3.0.0"
    }
  }
}
               
provider "rancher2" {
  api_url    = <rancher_api_url>
  access_key = <access_key>
  secret_key = <secret_key>
  insecure = true
}
               
resource "rancher2_cloud_credential" "rancher2_cloud_credential" {
  name = <cloud_credential_name>
  amazonec2_credential_config {
    access_key = <access_key>
    secret_key = <secret_key>
  }
}
               
resource "rancher2_cluster" "rancher2_cluster" {
  name = <cluster_name>
  eks_config_v2 {
    cloud_credential_id = rancher2_cloud_credential.rancher2_cloud_credential.id
    region = <region>    
    kubernetes_version = <kubernetes_version>
    node_groups {
      name = "node_group1"
      #instance_type = "t3.large"
      min_size = 1
      desired_size = 1
      max_size = 3
      launch_template {
        id = <launch_template_id>
        version = 2
}
    }    
    private_access = false
    public_access = true
  }
}
```
