### ISSUE TITLE
[Nightly build] Unable to update logging types for an EKS cluster or creating EKS with logging

### ISSUE THREAD

**Issue by valaparthvi** [rancher/eks-operator#938]
```
time="2024-11-15T12:33:55Z" level=error msg="Error removing metadata from failure message: message body not formatted as expected"
time="2024-11-15T12:33:55Z" level=error msg="Error recording ekscc [] failure message: Operation cannot be fulfilled on eksclusterconfigs.eks.cattle.io \"c-rmt4x\": the object has been modified; please apply your changes to the latest version and try again"
time="2024-11-15T12:33:55Z" level=error msg="error syncing 'cattle-global-data/c-rmt4x': handler eks-controller: error updating logging types: error updating cluster [c-rmt4x] logging types: operation error EKS: UpdateClusterConfig, https response error StatusCode: 400, RequestID: e8ab0fab-f178-4afb-9d7c-02a801a230d7, InvalidParameterException: Log type(s) not provided, requeuing"
```

I see the above error in logs when trying to update Logging. This error occurs on both UI and API updates.
The same error is also seen when an EKS cluster is created with logging enabled.

It also fails with the same error when logging is updated from the AWS console.

Operator Version: ttl.sh/eks-operator-nightly-20241115:1d
Rancher Version: v2.9-023781e52103c45a9bbdf3cb47d60b9336321daa-head

![image](https://github.com/user-attachments/assets/7d5d944d-5f7c-46e1-abc2-f84d332e72b9)

**Comment by valaparthvi** [comment]
The error seems to be related to AWS SDK [update](https://github.com/rancher/eks-operator/commits/release-v2.9/?since=2024-11-11&until=2024-11-15).

**Comment by valaparthvi** [comment]
@yiannistri Please note that the rancher version 2.9-head points to a [2-week old commit](https://github.com/rancher/rancher/commit/023781e52103c45a9bbdf3cb47d60b9336321daa).

**Comment by yiannistri** [comment]
@valaparthvi thank you for the info, I'll be testing this with the current HEAD for 2.9. Has this slipped into a recent release?

**Comment by valaparthvi** [comment]
Also, this is the command I used:
```
        helm upgrade --install rancher --devel rancher-latest/rancher \
                --version=2.9-head \
                --set rancherImageTag=v2.9-head \
                --namespace cattle-system --create-namespace \
                --set hostname=$hostname \
                --set replicas=1 \
                --set bootstrapPassword=adminadmin \
                --kube-insecure-skip-tls-verify \
                --wait
```

But I believe we need to use stgregistry. I managed to reproduce the above issue by running [GH action](https://github.com/rancher/hosted-providers-e2e/actions/runs/11850905373/job/33026542027) on nightly chart.

**Comment by valaparthvi** [comment]
>Has this slipped into a recent release?

Nope. I tested logging and ran the tests as well. It was working as expected. It's only the nightly build.

**Comment by yiannistri** [comment]
Using the new nightly images from today `ttl.sh/eks-operator-nightly-20241127:1d` I was not able to reproduce this error. I suspect this was due to a bug in the nightly workflow that produced images that were not exactly up to date and has since being fixed. Please try again and let me know if this is still reproducible.

**Comment by valaparthvi** [comment]
This is not reproducible anymore.
Tested on Rancher 2.10-head (e76fac95d5fa0d7821d0fffaf063f619d0930653), EKS Operator Nightly: 20241129.

I created an EKS cluster with logging enabled and then updated it via API, UI, and Cloud console; everything worked as expected.
