### ISSUE TITLE
Cover controller package with unit tests, ideally use envtest

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/eks-operator#94]
The controller package doesn't include any tests, we should add some.
Ideally, we can use envtest https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest for testing it but that will require some investigation.

This issue depends on https://github.com/rancher/eks-operator/issues/93 as I expect it will require some minor refactoring in controller package.

**Comment by furkatgofurov7** [comment]
Should be completed in #307
