### ISSUE TITLE
EKS:DescribeAddons should not be a required permission if EBS is not checked during cluster creation/update

### ISSUE THREAD

**Issue by valaparthvi** [rancher/eks-operator#951]
EKS:DescribeAddon is a required permission even if the EBS addon is not checked.

Rancher [docs](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/eks#ebs-csi-driver-addon-permissions) describe this permission as necessary in case the user wants to enabled EBS CSI Driver.

This is causing Rancher crash on 2.9, and error on 2.8 and 2.10, ref: https://github.com/rancher/rancher/issues/48144

The operator must check the config for EBS addon before deeming the permission to be necessary.

**Comment by yiannistri** [comment]
Closing in favour of https://github.com/rancher/rancher-docs/issues/1582
