### ISSUE TITLE
Create a setup for running E2E tests

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/eks-operator#96]
Create a setup for running E2E test, this includes following things:

- Add cloud credentials to the repository secrets
- Add a new github workflow similar to this, example: https://github.com/rancher/aks-operator/blob/master/.github/workflows/e2e-latest-rancher.yaml
- Add new makefile tasks for running e2e, example: https://github.com/rancher/aks-operator/blob/master/Makefile#L120
- Create an e2e package with suite setup, example:  https://github.com/rancher/aks-operator/tree/master/test/e2e

**Comment by furkatgofurov7** [comment]
Covered in https://github.com/rancher/eks-operator/pull/115, closing it. Feel free to re-open if anything is missing.
